language: python
python:
#- '2.7'
- '3.6'
install:
- pip install -r requirements/base.txt
- pip install -r requirements/development.txt
script:
- if [ $TRAVIS_BRANCH != "release" ]; then nosetests; fi
sudo: required
dist: xenial
deploy:
  provider: pypi
  user: __token__
  password: $PASSONE$PASSTWO
  on:
    distributions: sdist bdist_wheel
    repo: Mangopay/mangopay2-python-sdk
    branch: release
    tags: false
    python: 3.6
    condition: $TRAVIS_PYTHON_VERSION = "3.6"
env:
  global:
  - secure: eDsZz0hrnLpBmkFvHMeczHHjytOMJpOZMc21nVR/vRLnjZ7eLmXaklvdy3AQ5SJz+l1neVVihHNX6MyBJ0s63UKatLP7catl++yyqPj5/0C7C0a07ZvJHhUzqnEdYLNOMauy7p5rPMldLOiT1dgQlL1f1FG31BHJ5UkAnrhwvdU=
  - secure: sZ91Uh/9t4oQn34SUnkEE7opYHy1loe/q8YRG/zHDvY1Qwbzvu+lubKMQwtiHNuY7qJAxBdW5uf8+Poaj742tTTkhiM4Rfqh2FDgWz0DkzIJ7w6u72VGcvIGdaipZtddo70XU5noA4Hw24qmdIx4zbnpw1WsNc4PD6CB5b2rSBA=
